version: '2.3'
services:
  registry-srv:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - //opt/registry:/var/lib/registry
      - //opt/registry/srv-config.yml:/etc/docker/registry/config.yml
      
  registry-web:
    image: hyper/docker-registry-web
    ports:
      - 8000:8080
    volumes:
      - //opt/registry/web-config.yml:/conf/config.yml
    environment:
      - REGISTRY_URL=http://registry-srv:5000/v2
      - REGISTRY_NAME=localhost:5000

# mkdir /opt/registry && mv srv-config.yml web-config.yml -t /opt/registry/
# docker-compose up -d