apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-additional-rules
  namespace: monitoring
spec:
  groups:
    - name: general.rules
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.instance}} 采集器已停止工作"
          description: "{{$labels.instance}} 服务器延时超过5分钟"

      - alert: NodeCPUUsage
        expr: round(100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance) * 100)) > 80
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} CPU使用率过高！"
          description: "{{$labels.mountpoint }} CPU使用大于80%(目前使用:{{$value}}%)"

      - alert: NodeMemoryUsage
        expr: round(100 - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100) > 80
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} 内存使用率过高！"
          description: "{{$labels.mountpoint }} 内存使用大于80%(目前使用:{{$value}}%)"

      - alert: NodeFilesystemUsage
        expr: round(100 - (node_filesystem_free_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"} * 100)) > 80
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} 磁盘分区使用率过高！"
          description: "{{$labels.mountpoint }} 磁盘分区使用大于80%(目前使用:{{$value}}%)"

      - alert: NodeDiskIOUsage
        expr: round((avg(irate(node_disk_io_time_seconds_total[1m])) by(instance) * 100)) > 80
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} 流入磁盘IO使用率过高！"
          description: "{{$labels.mountpoint }} 流入磁盘IO大于80%(目前使用:{{$value}}%)"

      - alert: NodeNetworkReceive
        expr: round((sum(rate (node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance)) / 102400) > 300
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} 流入网络带宽过高！"
          description: "{{$labels.mountpoint }}流入网络带宽持续5分钟高于300M(目前使用:{{$value}}M)"

      - alert: NodeNetworkTransmit
        expr: round((sum(rate (node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance)) / 102400) > 300
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} 流出网络带宽过高！"
          description: "{{$labels.mountpoint }}流出网络带宽持续5分钟高于300M(目前使用:{{$value}}M)"

      - alert: NodeTCPCurrEstab
        expr: node_netstat_Tcp_CurrEstab > 3000
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.mountpoint}} TCP_ESTABLISHED过高！"
          description: "{{$labels.mountpoint }} TCP_ESTABLISHED大于3000(目前使用:{{$value}})"

      - alert: ProcessDown
        expr: namedprocess_namegroup_num_procs == 0
        for: 5m
        labels:
          status: critical
        annotations:
          platform: "测试环境"
          summary: "{{$labels.groupname}} 进程已停止工作！"
          description: "{{$labels.instance}} 服务器延时超过5分钟"
